// This file is auto-generated by scripts/generate-slides-index.js
import slide0 from '../slides/01_GitLab_Foundations_&_UI_Navigation.md';
import slide1 from '../slides/02_Mastering_Issue_Management_&_Integrated_Time_Tracking.md';
import slide2 from '../slides/03_Strategic_Labeling_&_Powerful_Filtering.md';
import slide3 from '../slides/04_Milestones_for_Timeboxing_&_Release_Planning.md';
import slide4 from '../slides/05_Epics_for_Structuring_Larger_Initiatives.md';
import slide5 from '../slides/06_Advanced_Issue_Board_Configurations_&_Workflow_Visualization.md';
import slide6 from '../slides/07_Roadmaps_for_Strategic_Visualization.md';
import slide7 from '../slides/08_Advanced_Git_Branching_Workflows_with_GitLab.md';
import slide8 from '../slides/09_CI_Foundations_&_Best_Practices.md';
import slide9 from '../slides/10_Leveraging_the_GitLab_Ecosystem_&_Integrations.md';
import slide10 from '../slides/11_Implementation_Planning_Session.md';

export const slidesIndex = [
  { name: '01_GitLab_Foundations_&_UI_Navigation', file: '01_GitLab_Foundations_&_UI_Navigation.md', import: slide0 },
  { name: '02_Mastering_Issue_Management_&_Integrated_Time_Tracking', file: '02_Mastering_Issue_Management_&_Integrated_Time_Tracking.md', import: slide1 },
  { name: '03_Strategic_Labeling_&_Powerful_Filtering', file: '03_Strategic_Labeling_&_Powerful_Filtering.md', import: slide2 },
  { name: '04_Milestones_for_Timeboxing_&_Release_Planning', file: '04_Milestones_for_Timeboxing_&_Release_Planning.md', import: slide3 },
  { name: '05_Epics_for_Structuring_Larger_Initiatives', file: '05_Epics_for_Structuring_Larger_Initiatives.md', import: slide4 },
  { name: '06_Advanced_Issue_Board_Configurations_&_Workflow_Visualization', file: '06_Advanced_Issue_Board_Configurations_&_Workflow_Visualization.md', import: slide5 },
  { name: '07_Roadmaps_for_Strategic_Visualization', file: '07_Roadmaps_for_Strategic_Visualization.md', import: slide6 },
  { name: '08_Advanced_Git_Branching_Workflows_with_GitLab', file: '08_Advanced_Git_Branching_Workflows_with_GitLab.md', import: slide7 },
  { name: '09_CI_Foundations_&_Best_Practices', file: '09_CI_Foundations_&_Best_Practices.md', import: slide8 },
  { name: '10_Leveraging_the_GitLab_Ecosystem_&_Integrations', file: '10_Leveraging_the_GitLab_Ecosystem_&_Integrations.md', import: slide9 },
  { name: '11_Implementation_Planning_Session', file: '11_Implementation_Planning_Session.md', import: slide10 }
];
